### ISSUE TITLE
SD-Card PullUp

### ISSUE THREAD

**Issue by moffel** [synogate/gameboy-fpga-cartridge#1]
The SD-Card interface requires pull-up's on DAT0, DAT1 and DAT2 in SPI mode. The pull-up on DAT0 is missing.

During tests the SD-Card did not respond at all. When enabling the FPGA weak-pull-up the SD-Card works as expected. However the weak-pull-up has a resistance of up to 45kOhm and varies a lot. This may hinder fast SPI clock speeds and is subject to silicon lottery. We should therefore add another pull-up to DAT0.

**Comment by Andreas-Ley** [comment]
I added 2k pullups to all data lines. For DAT1 and DAT2 I added two initially open solder bridges so we can still decide to pull them up or down.
