### ISSUE TITLE
improve audio interface 

### ISSUE THREAD

**Issue by moffel** [synogate/gameboy-fpga-cartridge#8]
The current circuit is unable to output below 1.12V, probably due to OpAmp limitations.
It is also not capable of outputting more than 3,44V.

When turning the potentiometer, the only effect is the rise time between min and max and how long we stay in min. This indicates that the OpAmp is limited in its range.

We should consider removing the OpAmp in case we cannot find more suitable parts.

**Comment by Andreas-Ley** [comment]
replaced the opamp with a rail2rail one.
